version: '3'

services:
  web:
    build: .
    container_name: pocket_daily
    env_file:
      - .env
    volumes:
      - .:/PocketDaily
    expose:
      - "8050"
    networks:
      - mynetwork
    depends_on:
      - psql

  nginx:
    image: nginx:latest
    container_name: pocket_daily_nginx
    ports:
      - "8050:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - mynetwork

  psql:
    image: postgres:16.3
    container_name: pocket_daily_db
    environment:
      POSTGRES_DB: pocket_daily
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: PocketDaily
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  postgres_data:
