"""Initial Migrate

Revision ID: df27a2d871f6
Revises: 
Create Date: 2024-06-23 16:14:24.444792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df27a2d871f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_state',
    sa.Column('line_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('RANDOM_INT', 'ADVENTURE_GAME', name='userstateenum'), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('history_messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('line_id')
    )
    with op.batch_alter_table('user_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_state_line_id'), ['line_id'], unique=True)

    op.create_table('user_input_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_state_line_id', sa.String(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_state_line_id'], ['user_state.line_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_input_history')
    with op.batch_alter_table('user_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_state_line_id'))

    op.drop_table('user_state')
    # ### end Alembic commands ###
